#
# Autor : Michal Lukac, xlukac05@stud.fit.vutbr.cz
# Popis : Makefile pre projekt do predmetu IPK na VUT FIT

CC=g++
CFLAGS=-std=c++98 -Wall -Wextra -pedantic

webinfo:
	$(CC) $(CFLAGS) webinfo.cpp -o webinfo
