# Autor  : Michal Lukac, xlukac05@stud.fit.vutbr.cz
# Projekt: Makefile pre 2.projekt do predmetu IOS na VUT FIT.

CC=gcc
CFLAGS=-std=gnu99 -Wall -Wextra -Werror -pedantic -lrt
EXE=barbers

$(EXE): barbers.c
	$(CC) $(CFLAGS) $^ -o $(EXE)
