#
# Autor : Michal Lukac, xlukac05@stud.fit.vutbr.cz
# Popis : Makefile pre projekt do predmetu ISA na VUT FIT

CC=g++
CFLAGS=-g -O2 -o model -lsimlib -lm

making:
	$(CC) $(CFLAGS) model.cc -o model
run:
	./model
