#
# Autor : Michal Lukac, xlukac05@stud.fit.vutbr.cz
# Popis : Makefile pre projekt do predmetu ISA na VUT FIT

CC=g++
CFLAGS=-std=c++98 -Wall -Wextra -pedantic

making:
	$(CC) $(CFLAGS) main.cpp -o mypmtud

