#
# Autor : Michal Lukac, xlukac05@stud.fit.vutbr.cz
# Popis : Makefile pre projekt do predmetu IPK na VUT FIT

CC=g++
CFLAGS=-std=c++98 -Wall -Wextra -pedantic

making:
	$(CC) $(CFLAGS) client.cpp -o client
	$(CC) $(CFLAGS) -pthread server.cpp -o server